### ISSUE TITLE
Support latest IntelliJ IDEA

### ISSUE THREAD

**Issue by wheeOs** [tbm98/flutter_generator_snippets#62]
Really handy snippets!
Since I had to upgrade IntelliJ to the 2022 versions the plugin is not compatible anymore..
Could you please make it compatible?

**Comment by tbm98** [comment]
@wheeOs yes. I will update soon.

**Comment by tbm98** [comment]
Hi @wheeOs. You can install from the disk this [file](https://github.com/tbm98/flutter_generator_snippets/suites/6107793544/artifacts/212137640) or wait for next release on store

**Comment by wheeOs** [comment]
@tbm98 great thanks!
