### ISSUE TITLE
freezed template contains json_serializable code

### ISSUE THREAD

**Issue by paricleu** [tbm98/flutter_generator_snippets#67]
The freezed templates contain json serializable code.
Specifically the 'part *.g.dart' and the '@JsonSerializable" annotation.

![Screenshot 2023-02-07 at 22 13 02](https://user-images.githubusercontent.com/48349235/217367481-c75b99a5-386e-47db-b1e3-a6cf3b125569.png)

**Comment by tbm98** [comment]
Hi @paricleu.
I have been removing @JsonSerializable but still keep *.g.dart in the new version.
if you don't use json serializable, you can manually remove it.
